language: go
sudo: false
go:
  - 1.7
install:
  - go get github.com/vkuznet/cmsauth
  - go get github.com/vkuznet/das2go
  - go get github.com/vkuznet/x509proxy
  - go get github.com/buger/jsonparser
